name: Docker Image CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USER}} -p ${{ secrets.DOCKER_SECRET }}

    - name: Push Docker image
      run: docker push my-image-name:$(date +%s)
