name: Docker Image CI

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set image tag
      id: set_image_tag
      run: echo "::set-output name=IMAGE_TAG::$(date +%s)"
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:${{ steps.set_image_tag.outputs.IMAGE_TAG }}

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_SECRET }}

    - name: Push Docker image
      run: docker push my-image-name:${{ steps.set_image_tag.outputs.IMAGE_TAG }}
